### ISSUE TITLE
NeoForge 1.20.4 supports

### ISSUE THREAD

**Issue by Lolothepro** [hashalite/Freecam#149] opened 2024-01-02 20:59 UTC
I noticed that Freecam (Modrinth) 1.20.2 currently only supports Forge, is it possible to add NeoForge support (1.20.4)?

**Comment by MattSturgeon** [comment] 2024-01-02 21:39
Duplicate of #133.

This has been added, it just hasn't made it into a release yet.

**Closed** 2024-01-04 06:40 UTC
